### PR TITLE
Add Page number alteration snippets

### PR DESCRIPTION
**Pull request by dbolack-ab**
This creates Text Editor Menu Snippets for the new SkipCounting and ResetCounting classes used by the auto page numbering system.

 - [x] The  Icons and labels might not be the best. Suggestions welcome
 - [x] It might be wise to move this to a Subsnippet menu for all the page numbering snippets. Discuss?
 - [x] Presently, the ToC snippet will generate entries on pages that have the skipCounting class. Should those entries be discarded as they will be inaccurate or should we consider that a user error?

This PR is a child of #3639.

### CODE REVIEW

**Comment by 5e-Cleric** [comment]
> The Icons and labels might not be the best. Suggestions welcome
Could we get a deployment for this?

> It might be wise to move this to a Subsnippet menu for all the page numbering snippets. Discuss?

I think i agree

Presently, the ToC snippet will generate entries on pages that have the skipCounting class. Should those entries be discarded as they will be inaccurate or should we consider that a user error?

ToC should be as accurate as we can, yes, jump entries in pages without numbering.

**Comment by 5e-Cleric** [comment]
blocked merging until #3639 , but we can review

**Comment by calculuschild** [comment]
@dbolack-ab Thank you for splitting this up

- For icons, I might suggest `rotate-left` for the RESET, and `xmark` for SKIP
- I agree, we have multiple numbering-related snippets now. Let's combine them into a group
- `.skipCounting` entries should not be included in the TOC in my opinion (but this should be handled in #3639)

**Review by 5e-Cleric — APPROVED** [review]
Functionality works, good icons, this looks good

**Pull request merged**
