### PR TITLE
Update table of content list-item breakage rules for wide table of contents

### PR DESCRIPTION
**Pull request by dbolack-ab**
Simple CSS fix as noted in Issue to disable normal list break-avoidance. 

Solves #2563

### CODE REVIEW

**Review by 5e-Cleric — APPROVED** [review]

**Review by G-Ambatte — APPROVED** [review]
Tested and confirmed that this allows lists to cross automatic column breaks, resolving attached issue #2563.

**Comment by 5e-Cleric** [comment]
Wait, isn't this to make ToC auto cut in columns?

image

**Comment by G-Ambatte** [comment]
Using this reproduction text:

```
{{toc,wide
# Contents

- ### [{{ Test 1}}{{ 2}}](#p2)
  - #### [{{ Test A}}{{ 2}}](#p2)
  - #### [{{ Test B}}{{ 2}}](#p2)
  - #### [{{ Test C}}{{ 2}}](#p2)
  - #### [{{ Test D}}{{ 2}}](#p2)
  - #### [{{ Test E}}{{ 2}}](#p2)
  - #### [{{ Test F}}{{ 2}}](#p2)
  - #### [{{ Test G}}{{ 2}}](#p2)
  - #### [{{ Test H}}{{ 2}}](#p2)
  - #### [{{ Test I}}{{ 2}}](#p2)
  - #### [{{ Test J}}{{ 2}}](#p2)
  - #### [{{ Test K}}{{ 2}}](#p2)
  - #### [{{ Test L}}{{ 2}}](#p2)
  - #### [{{ Test M}}{{ 2}}](#p2)
  - #### [{{ Test N}}{{ 2}}](#p2)
  - #### [{{ Test O}}{{ 2}}](#p2)
  - #### [{{ Test P}}{{ 2}}](#p2)
  - #### [{{ Test Q}}{{ 2}}](#p2)
  - #### [{{ Test R}}{{ 2}}](#p2)
  - #### [{{ Test S}}{{ 2}}](#p2)
  - #### [{{ Test T}}{{ 2}}](#p2)
  - #### [{{ Test U}}{{ 2}}](#p2)
  - #### [{{ Test V}}{{ 2}}](#p2)
  - #### [{{ Test W}}{{ 2}}](#p2)
  - #### [{{ Test X}}{{ 2}}](#p2)
  - #### [{{ Test Y}}{{ 2}}](#p2)
  - #### [{{ Test Z}}{{ 2}}](#p2)
}}


\page


# Test 1

## Test A

## Test B

## Test C

## Test D

## Test E

## Test F

## Test G

## Test H

## Test I

## Test J

## Test K

## Test L

## Test M

## Test N

## Test O

## Test P

## Test Q

## Test R

## Test S

## Test T

## Test U

## Test V

## Test W

## Test X

## Test Y

## Test Z
```

Production:
image

Deployment:
image

**Comment by 5e-Cleric** [comment]
ah, i see, even columns, not column breaking on page end, alright then.

**Review by 5e-Cleric — APPROVED** [review]

**Comment by 5e-Cleric** [comment]
It is a fine fix, but i am concerned it may broke brews, imagine if someone has this setup in their brew:

image


### With the new changes, their document becomes:

image


Granted, a column break correctly placed fixes this, users may not see it that obvious.

**Comment by dbolack-ab** [comment]
> Granted, a column break correctly placed fixes this, users may not see it that obvious.

We could make this a V4 thing if there's plans for a V4 demarcation in the near future?

**Comment by 5e-Cleric** [comment]
I'd merge

**Comment by dbolack-ab** [comment]
Seems like the correct fix for that single column case would be to create a tocSingle class that is designed for this situation, with alternating left/right based on page number or a tocSingleLeft and tocSingleRight for more explicit declaration.

**Comment by calculuschild** [comment]
Well, you would just take out the `wide` to make it single column.

**Comment by calculuschild** [comment]
Mmmmmk fellas. Gonna just merge this. If people get mad tell them its my fault.

**Pull request merged**
