### PR TITLE
Added new editor theme named darkvision

### PR DESCRIPTION
**Pull request by RKuerten**
This is a new dark theme for the editor. I called it darkvision, but it is quite colorful. 

I created this one because I felt the others didn't have colors for all things and mainly the colors for the term :: definition thing has really bad colors on dark themes

**Brew Editor**
image

**Theme Editor**
image

### CODE REVIEW

**Comment by 5e-Cleric** [comment]
How does the Style tab look with this theme?

**Comment by 5e-Cleric** [comment]
Weird

pulled this changes manually (copypaste) into my local, and some stuff works while other doesn't
image

**Comment by 5e-Cleric** [comment]
I recommend an addition:
```
    .define:not(.term):not(.definition) {
        background:#333;
    }
```

**Comment by 5e-Cleric** [comment]
`cm-error` by itself (like a bad selector) has no styling, should fix that.

you can easily check it by making nested css, which works but codemirror 5 does not show as correct.

your code could benefit from css nesting too:

```
.cm-s-default .cm-link {
    color: #dd6300;
}
/* links */
.cm-s-default .cm-string {
    color: #aa8261;
}
```

is equal to
```
.cm-s-default {
    .cm-link {
        color: #dd6300;
    }
    /* links */
    .cm-string {
        color: #aa8261;
    }
}
```

**Comment by RKuerten** [comment]
Finished cleaning up, let me know if there is something else you think it needs to be changed @5e-Cleric

**Review by 5e-Cleric — APPROVED** [review]

**Comment by 5e-Cleric** [comment]
Thanks @RKuerten !

**Pull request merged**
