### PR TITLE
Tweak CM page line brightness on dark themes

### PR DESCRIPTION
**Pull request by G-Ambatte**
As per Reddit report (https://redd.it/1d8opte), on dark CodeMirror themes, it can be difficult to read the folded text between the bright backgrounds of `\page` lines. This PR tweaks the brightness down slightly by reducing opacity of the background from 75% to 50%.

### CODE REVIEW

**Comment by G-Ambatte** [comment]
Visual preview of the change:

image

**Comment by 5e-Cleric** [comment]
Talk about a minor change...

when you're showing the change, it'd help more to see a comparison from old to new.

Also, this is an unnecessary change that depends too much on personal taste.

**Comment by dbolack-ab** [comment]
> Also, this is an unnecessary change that depends too much on personal taste.

If so, should we then fork this particular theme for both tastes or is that too far?

**Comment by 5e-Cleric** [comment]
> > Also, this is an unnecessary change that depends too much on personal taste.
> 
> If so, should we then fork this particular theme for both tastes or is that too far?

i don't think anyone would notice the change.

**Comment by Gazook89** [comment]
> fork the theme

I wonder if it's best to start making modifications to individual themes.  Not necessarily solely for the reason raised in this PR, but it might be something we have more and more reasons for over a long enough time.  And getting used to that *now*, rather than realizing we missed the opportunity far in the future, might be good.

We will have more and more custom syntax, widgets (*some day*), and other editor enhancements that could all benefit from thematic style customizations.  For example, right now we are only modifying the codemirror instance-- but I could see a future where the Snippet Bar and Menus are matched to the codemirror theme.  Are we offering the opportunity to customize the "Editor" (which to me includes the Editor Tools aka the snippets) or just the writing space?   I'd say we allow themes to change the whole Editor.

That's a whole other thing, though.  For *this* PR, I think the change is minor, it's specific to dark themes, doesn't make things worse, and easily reversible.  

Just for reference, here is the original reddit users screenshot of the existing styling:
dark theme

**Review by Gazook89 — APPROVED** [review]
Looks good to me

**Review by 5e-Cleric — APPROVED** [review]

**Review by Gazook89 — APPROVED** [review]
try this again....

looks good to me!

**Review by dbolack-ab — APPROVED** [review]
Looks good.

**Review by dbolack-ab — APPROVED** [review]

**Review by 5e-Cleric — APPROVED** [review]
looks good to me too

**Review by dbolack-ab — APPROVED** [review]

**Pull request merged**
