### PR TITLE
Add DiceFont support to Homebrewery

### PR DESCRIPTION
**Pull request by G-Ambatte**
This PR adds the DiceFont icons to Homebrewery.

The following is the source of an example document, showcasing the icons added by this PR.

```
# Dice Icons
:
### D4
{{df,df-d4-1}}{{df,df-d4-2}}{{df,df-d4-3}}{{df,df-d4-4}}

### D6
{{df,df-d6-1}}{{df,df-d6-2}}{{df,df-d6-3}}{{df,df-d6-4}}{{df,df-d6-5}}{{df,df-d6-6}}  
{{df,df-dot-d6-1}}{{df,df-dot-d6-2}}{{df,df-dot-d6-3}}{{df,df-dot-d6-4}}{{df,df-dot-d6-5}}{{df,df-dot-d6-6}}  
{{df,df-small-dot-d6-1}}{{df,df-small-dot-d6-2}}{{df,df-small-dot-d6-3}}{{df,df-small-dot-d6-4}}{{df,df-small-dot-d6-5}}{{df,df-small-dot-d6-6}}  
{{df,df-solid-small-dot-d6-1}}{{df,df-solid-small-dot-d6-2}}{{df,df-solid-small-dot-d6-3}}{{df,df-solid-small-dot-d6-4}}{{df,df-solid-small-dot-d6-5}}{{df,df-solid-small-dot-d6-6}}

### D8
{{df,df-d8-1}}{{df,df-d8-2}}{{df,df-d8-3}}{{df,df-d8-4}}{{df,df-d8-5}}{{df,df-d8-6}}{{df,df-d8-7}}{{df,df-d8-8}}

### D10

{{df,df-d10-1}}{{df,df-d10-2}}{{df,df-d10-3}}{{df,df-d10-4}}{{df,df-d10-5}}{{df,df-d10-6}}{{df,df-d10-7}}{{df,df-d10-8}}{{df,df-d10-9}}{{df,df-d10-10}}

### D12
{{df,df-d12-1}}{{df,df-d12-2}}{{df,df-d12-3}}{{df,df-d12-4}}{{df,df-d12-5}}{{df,df-d12-6}}{{df,df-d12-7}}{{df,df-d12-8}}{{df,df-d12-9}}{{df,df-d12-10}}{{df,df-d12-11}}{{df,df-d12-12}}

### D20
{{df,df-d20-1}}{{df,df-d20-2}}{{df,df-d20-3}}{{df,df-d20-4}}{{df,df-d20-5}}{{df,df-d20-6}}{{df,df-d20-7}}{{df,df-d20-8}}{{df,df-d20-9}}{{df,df-d20-10}}{{df,df-d20-11}}{{df,df-d20-12}}{{df,df-d20-13}}{{df,df-d20-14}}{{df,df-d20-15}}{{df,df-d20-16}}{{df,df-d20-17}}{{df,df-d20-18}}{{df,df-d20-19}}{{df,df-d20-20}}
```

The result should look like this:
image

### CODE REVIEW

**Comment by 5e-Cleric** [comment]
can we get a preview as to how the fonts look like? even if it's just an image

**Comment by G-Ambatte** [comment]
> can we get a preview as to how the fonts look like? even if it's just an image

I have added a screen grab to the initial comment now.

**Comment by G-Ambatte** [comment]
Screen grab with unnumbered dice glyphs included:

image

**Comment by 5e-Cleric** [comment]
This syntax is too long, and does not match our Edelberry icons font, i propose moving from `{{df,df-d4-1}}` to `{{df,d4-1}}`.

**Comment by 5e-Cleric** [comment]
Once this PR is done, we might want to include these icons in some snippets, or put our work into the icon picker.

**Review by 5e-Cleric — APPROVED** [review]

**Comment by 5e-Cleric** [comment]
> Screen grab with unnumbered dice glyphs included:

the actual font also includes these two:
image

But i don't think they have classes assigned.

**Pull request merged**
