### PR TITLE
U+00D1 and U+00F1 fix

### PR DESCRIPTION
**Pull request by 5e-Cleric**
Fixes https://github.com/naturalcrit/homebrewery/issues/2280 by using the legacy font file in v3 too.

### CODE REVIEW

**Comment by calculuschild** [comment]
We definitely do not want to use the Legacy font in V3. The V3 font fixes several other issues with that existed in the Legacy font. Just fixing one character is not a good enough tradeoff.

What we actually want to do is go into the V3 font and just add the missing character.

**Comment by 5e-Cleric** [comment]
>  The V3 font fixes several other issues with that existed in the Legacy font. 

did not know that! well then i'll add the missing characters.

What were the other issues? so i can avoid making them.

**Comment by calculuschild** [comment]
Issues included:

- Badly-formed glyphs (self-intersecting paths, etc)
- Inconsistent character size
- Inconsistent character spacing
- Uneven vertical alignment
- Other missing characters
- Invalid metadata

As long as you just add the new characters and don't touch the others, it should be fine. Probably easiest is to just duplicate the normal 'n' so it's already sized and spaced, then put the tilde on top.

**Comment by calculuschild** [comment]
Oh also, check the new font wife by wife with the original v3 font. I've noticed some font editors re-encode things and it makes the characters thicker than before.

**Comment by 5e-Cleric** [comment]
For the last commit i took the v3 font and manually created the following glyphs: Ñ, ñ, ç, Ç, Ý, ý, #, ^, ¿, ', ", ¡, ·

The characters do not seem to have gotten thicker.

**Comment by calculuschild** [comment]
Perhaps if you can take a screenshot of the two fonts side by side to make it easier to compare and make sure nothing got broken.

**Comment by 5e-Cleric** [comment]
Wait, there is an error in the font metadata, bc of the editor

**Comment by 5e-Cleric** [comment]
image
In the left(Ñ and first A) the new version, in the right, the V3 one. they are exactly the same

**Comment by calculuschild** [comment]
Can you screenshot the whole alphabet in use on the website? To compare font letter spacing and sizing?

**Comment by 5e-Cleric** [comment]
The next step would be to add those characters in italics, bold and bold italics, but i don't think that is as prioritary, as per the dnd style that font is never used in caps or in italics.

**Comment by 5e-Cleric** [comment]
> Can you screenshot the whole alphabet in use on the website side by side with the original? To compare font letter spacing and sizing?

You mean a document with lorem ipsum? sure

**Comment by ericscheid** [comment]
> > Can you screenshot the whole alphabet in use on the website side by side with the original? To compare font letter spacing and sizing?
> 
> You mean a document with lorem ipsum? sure. But with special characters?

Don't need filler text, do need letters for comparison:

````
{{wide
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz (V3)
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz (new font)

ÅÑÜØetc (V3)
ÅÑÜØetc (new font)
}}
````

**Comment by 5e-Cleric** [comment]
image

**Review by calculuschild — CHANGES_REQUESTED** [review]
There appears to be some strange spacing issues on the new characters. For instance I would expect Ñ and N to have the same spacing between adjacent characters:

image

This test file is here in case it's helpful to copy it for testing: https://homebrewery.naturalcrit.com/share/2bpr4wLt4Knu Note that not all characters need to match necessarily (\* and ^ for example), but at least for the alphabetic characters there should be more consistency.

**Comment by 5e-Cleric** [comment]
fixed it, should have the exact same width now, most of them.

Note: italics, bold and bold italics should also be changed, but unless someone wants to pick it up from here, i am done with editing fonts.

**Comment by calculuschild** [comment]
Something is still off. It looks like the characters are not centered properly.

image

**Edit:** I had some time and went ahead and fixed it. Looks like the Left and Right Side Bearings were not quite right.

image

**Comment by calculuschild** [comment]
Thanks @5e-Cleric ! 💯 :tada: ⭐

**Pull request merged**
