### PR TITLE
Fix Nav flow

### LINKED ISSUE #2071: Awkward flow in navbar when brew title is long
This is a minor thing that's bothered me for awhile, sorry to open an issue on it:   When a brew title is long, and goes to two lines, the navbar height increases but the nav items come out looking odd.  

image

A simple solution is to make the nav items flexboxes, and vertically center the fontawesome icons.  It looks like this:

two line title

And with single line title:
single line title

The CSS changed is this:
```css
nav .navItem {
	-webkit-transition: background-color .25s ease;
	-moz-transition: background-color .25s ease;
	-o-transition: background-color .25s ease;
	transition: background-color .25s ease;
	padding: 8px 12px;
	cursor: pointer;
	background-color: #333;
	font-size: 10px;
	font-weight: 800;
	color: white;
	text-decoration: none;
	text-transform: uppercase;
	line-height: 13px;
	display: flex;  /* added these three items */
	align-items: center;
	justify-content: center;
}
```

I can create a PR quickly if interested.  I looked at it in both Chrome and FF.

### PR DESCRIPTION
**Pull request by 5e-Cleric**
Fixes #2071

### CODE REVIEW

**Comment by 5e-Cleric** [comment]
Still would need to work out something for actual flow of the nav to a sidebar or something like that, for mobile or screens smaller than 1200px

**Comment by 5e-Cleric** [comment]
Hmm, tests are failing because less version was updated, but not on vitreum.git

**Comment by Gazook89** [comment]
image

this is what the deployment looks like on my phone. It’s /new, and there is no title, so it seems to be shrinking that piece to nearly nothing

**Comment by calculuschild** [comment]
Seems fine to me. Merging!

Thanks @5e-Cleric ! 💯 ⭐ 🎉

**Pull request merged**
