### PR TITLE
Download Brew Source as Text File

### PR DESCRIPTION
**Pull request by G-Ambatte**
# Download Brew Source

## Purpose

The purpose of this branch is to allow users to download the source of a brew as a plain text file.

### Work Completed So Far

- [x] Create code module to output Brew source as a text file
- [x] Add a new page (`download`) to get the Brew source using its ID
- [x] Incorporate the "Download" option into nav bar on Share page
- [x] Incorporate download option in brew items on User page

### Considerations

- [x] Lint/CircleCi - The 200 line maximum requires that the code for the new page is moved to a new module, which I have called `sourceFunctions.jsx` in the `sharePage` directory. It seemed logical to also move the code for the existing "source" page here as well, as large portions of the two functions are identical.
- [x] "Source" vs "Download Source" in Share page nav bar - I have changed the button text from "Source" to "View Source", to better differentiate the function of the two buttons.

## Conclusion

This functionality has been requested previously (e.g. #1129, or [this workaround in JS from Reddit](https://redd.it/aerj7c)). This also goes some way towards a user being able to download all of their brews at once, either as several text files or a single ZIP archive.

It's probably not the cleanest code I've ever written and it's well past midnight so I'm doing this with only one eye opened as I write this PR, so I'd appreciate any feedback that you might have.
-- G

---

EDIT: These changes should also fix the issue reported with the unmodified ampersand in the HTML source as reported in issue #1188. I added the check and replacement strings as a key/value array, so it should simplify adding any further items to be replaced in the future, if any more should be discovered.

### CODE REVIEW

**Comment by G-Ambatte** [comment]
Shifted the functions back into `server.js` and removed both the unnecessary changes to `Homebrew.Model.js` and the new module. Only four files are now affected by this change, at least two of which are trivial changes.
At this point, I haven't got a working NaturalCrit login system yet, so I've been unable to test with a logged in user yet, and by extension, any of the GoogleActions.

- [ ] Test functionality with Google brews

**Comment by G-Ambatte** [comment]
- [x] Test functionality with Google brews

Login system now working, including Google linking. Download confirmed working identically for Google-stored brews as it does for locally stored brews.

Discussion points:
- [ ] **Download filename prefix:** Prefixing the filename with "Homebrewery-" makes for quite a long filename. Would this feature benefit from a shorter filename prefix, e.g. "HB-"?
- [ ] **Other issues:** What else have I forgotten to consider?

**Comment by G-Ambatte** [comment]
`/download` appears to be working correctly in all respects, for all brews - local and on Google drive.

**Comment by calculuschild** [comment]
@G-Ambatte Just need the config value for `const prefix = config.get('name_prefix');` in `server.js`, since the config file is missing from this PR. Can you remind me what we wanted to use for that?

Gonna try to trim down the Server.js since a lot of stuff is duplicated between HB and Google brews (replacing `<` with `&lt`, prepping the file for download, etc). This does reveal a lot of other duplicated stuff in the other URLs as well so I might refactor those as well.

**Comment by G-Ambatte** [comment]
> @G-Ambatte Just need the config value for `const prefix = config.get('name_prefix');` in `server.js`, since the config file is missing from this PR. Can you remind me what we wanted to use for that?

I was using "Homebrewery' but Gazook89 suggested "HB", which I have no objections to. From memory, I moved it to a config item so it could easily be changed later but also so I didn't actually have to make that decision at the time.

**Comment by calculuschild** [comment]
Ok. I'm just cleaning up the duplicated functions a bit and then this can merge and go out with v2.11.0

**Pull request merged**
