### PR TITLE
Fix for the colons in codeblocks issue.

### PR DESCRIPTION
**Pull request by dbolack-ab**
This was the lightest-weight solution I could find without potentially breaking definition lists for the `:` in codeblocks concern.

It may be a better fix to promote this to a proper token, I am unsure.

- [x] Catches `:` series
- [x] Does not interfere with DF Lists
- [x] Does not translate inside of PRE blocks.

Solves #1469

### CODE REVIEW

**Comment by calculuschild** [comment]
Rather than modifying the `code` renderer, this should be done by just adding a Marked extension that finds `:::` tokens. `code` tokens should already be smart enough to ignore Markdown syntax inside if that syntax is properly registered as a Marked extension.

**Comment by dbolack-ab** [comment]
> Rather than modifying the `code` renderer, this should be done by just adding a Marked extension that finds `:::` tokens. `code` tokens should already be smart enough to ignore Markdown syntax inside if that syntax is properly registered as a Marked extension.

Hence my second paragraph. However, getting it to not battle it out with the definition lists has proven a larger challenge than expected.

**Comment by dbolack-ab** [comment]
Found my problem with making it a token, however I do not know if we have any weird user cases this may break.

**Comment by calculuschild** [comment]
I just fiddled around a bunch looking for more edge cases. Found a few and added them as tests, then made small tweaks to get those tests passing.

I can't seem to find any more undesired behaviors so I think this is good to merge.

**Pull request merged**
