### PR TITLE
Fix var name substring clash #3613

### LINKED ISSUE #3613: Markdown: Functions break if a variable name is a substring of the function names
### Your idea:

During development of #3587, I discovered that `abs(a)` did not work, but `abs(c)` did.

Exhaustive testing for `abs()`:
image

Initial testing for `floor()`:
image

As can be seen, in every case where a variable name used in that calculation is a substring of the function name, the function stops working.

My suspicion is that the issue lies here, `shared/naturalcrit/markdown.js:line 465`:
image

By replacing _every_ instance of the variable name, we are catching unintended characters. Instead, we need to only replace the instances identified in the original regex match.

### PR DESCRIPTION
**Pull request by G-Ambatte**
This PR resolves #3613.

This PR changes the regex of the variable name replacement, to ensure that names that are substrings of math functions or other variables are not unintentionally replaced.

CURRENT:
```
[a]:-4

$[abs(a)]
```
**OUTPUT:** `$[abs(a)]`

image

PR:
```
[a]:-4

$[abs(a)]
```
**OUTPUT:** `4`

image

### CODE REVIEW

**Review by 5e-Cleric — COMMENTED** [review]
Would need to test this before approving, can we get a deployment?

**Comment by calculuschild** [comment]
> Would need to test this before approving, can we get a deployment?

Deployment live

**Comment by 5e-Cleric** [comment]
Can confirm this works, tested with `min()` because `abs()` is not live in the actual site.

`$[min()]` returns `<p>Infinity</p>`, is this expected behaviour?

**Comment by G-Ambatte** [comment]
> Can confirm this works, tested with `min()` because `abs()` is not live in the actual site.

`abs()` is not live in Production, but IS live in master, so should work in the deployment.

> `$[min()]` returns `<p>Infinity</p>`, is this expected behaviour?

This matches the function in the currently live Production, so I'm going to say "yes", but hesitantly.

---

REPRODUCTION BREW IN DEPLOYMENT: https://homebrewery-pr-3624.herokuapp.com/share/wSI_KF8CbN6N

**Comment by calculuschild** [comment]
Very nice. Good debugging on this one!

**Pull request merged**
