### PR TITLE
[DX] Update ESLint rules

### LINKED ISSUE #3906: [DX] ESLint throws errors on Import Attributes
### Your idea:

When using the new syntax for `import` (e.g. `import X from Y with { type: 'json' };`), ESLint throws an unexpected token error on the `with` keyword.

### PR DESCRIPTION
**Pull request by G-Ambatte**
This PR resolves #3906.

This PR adds the `@babel/plugin-syntax-import-assertions` package as a dev dependency, and adds it to the list of Babel plugins in the config file. This prevents the "unexpected token" error on the `with` keyword.

### CODE REVIEW

**Comment by calculuschild** [comment]
Just for clarity, this doesn't actually update the ESLint rules, but rather tells Babel to convert it to something different so ESLint doesn't see it.

This Babel Rule is also deprecated, since `assert` has been discarded in favor of `with`. https://babeljs.io/docs/v8-migration#babelplugin-syntax-import-assertions

So while this works, I think it may be more appropriate to find the ESLint setting (perhaps converting to their @stylistic plugin) rather than using Babel to convert to a deprecated syntax.

What do you think? At a minimum I think we should add a comment explaining why we are using a deprecated babel plugin since it's not obvious its just to make ESLint happy.

**Comment by G-Ambatte** [comment]
Actually, the spec just reached Stage 4 (at the start of last month - Oct 2024) and it should now be live in ESLint? Searching the repo, I found a lot of rules in ESLint's `camelcase.js` from v9.14 and up, which we're already using... so it might be possible without requiring a new package.

The package WAS the recommended way to make it work. I'll leave this PR open while I look into whether the ESLint config can be modified to achieve the same result.

**Comment by calculuschild** [comment]
You are right, this is a very recent spec change. Based on this link you shared in Gitter, I'm wondering if there is some deprecated ESLint Formatting Rule we use that is the culprit.

https://eslint.org/blog/2024/11/eslint-v9.14.0-released/

**Comment by G-Ambatte** [comment]
It appears to be working now, without this PR merged... No additional package and no config changes required.

**Comment by calculuschild** [comment]
Ok, I just checked this. I have ESLint 9.15.0 installed and I am not seeing this issue on my end. I think you may have just needed some kind of refresh or install to catch up to the latest version. I'm going to close this and the issue for now.

**Pull request closed without merging**
