### PR TITLE
WIP: Add UserInfo framework

### PR DESCRIPTION
**Pull request by G-Ambatte**
This PR adds the initial framework of a UserInfo MongoDB database collection.

The intention of the UserInfo collection is to store user information, such as preferences (renderer: legacy/v3) or default themes (once implemented). It is also possible that the UserInfo collection could be used to store notification or other user messaging data.

### CODE REVIEW

**Comment by calculuschild** [comment]
Closing. This needs further discussion on the underlying issue to make sure how/whether this needs to be handled going forward.

Also needs an Issue where we can have this discussion.

**Comment by calculuschild** [comment]
Reopening now that #1908 has been outline. Refer to that issue for our approach for this feature.

**Comment by G-Ambatte** [comment]
Something's gone wrong with the merge on this PR, I'm going to close out this PR and create a fresh branch from the current master.

**Comment by 5e-Cleric** [comment]
> Something's gone wrong with the merge on this PR, I'm going to close out this PR and create a fresh branch from the current master.

Was this done?

**Pull request closed without merging**
