### PR TITLE
Change dropdowns to stay open when clicked

### LINKED ISSUE #2702: Add ability to *click* on username to open that dropdown menu
### Your idea:

Right now the user menu drops down when you hover over the username on the toolbar.  We should add ability to click on that to *keep* the menu available.  This would be more accessible.

Actually, this should probably be done on most of the toolbar options.

https://old.reddit.com/r/homebrewery/comments/11dx5vy/issue_pull_down_menu/

### LINKED ISSUE #2782: Recent Items menu dropdown is inconsistent with other menu dropdowns
### Renderer

v3

### Browser

Chrome

### Operating System

Windows

### What happened?

The Recent Items (Edited/Viewed) dropdown menu is inconsistent with the other dropdown menus.

- appears instantly/not animated
- different HTML structure and classes

The content of the Recent Items dropdown may just need to be shifted to the existing Nav dropdown container framework.

### Code

_No response_

### PR DESCRIPTION
**Pull request by G-Ambatte**
This PR resolves #2702.
It also fixes #2782.

This PR changes the behavior of the Nav.dropdown to always open on click, and not close until the ClickOutside function is triggered.
It also shifts the Recently Viewed/Edited dropdown menu item to use the Nav.dropdown React component, which it previously did not.

**Can be tested at https://homebrewery-pr-2901.herokuapp.com/**

### CODE REVIEW

**Comment by Gazook89** [comment]
On iOS I don’t get that problem. I click on Need Help, and it just stays open without taking me anywhere else. On the Edit page. 

It is possible to open two menus at once though

**Comment by 5e-Cleric** [comment]
In windows works fine, don't know if users will notice this change, but it is good.

**Review by omjaz909 — CHANGES_REQUESTED** [review]

**Comment by Gazook89** [comment]
On macOS in firefox, I can click outside the opened menu and it doesn't dismiss the opened menu.  Clicking on another menu (for example, if Need Help is opened, I click on Recent Items) closes the first menu.

**Comment by G-Ambatte** [comment]
> On macOS in firefox, I can click outside the opened menu and it doesn't dismiss the opened menu. Clicking on another menu (for example, if Need Help is opened, I click on Recent Items) closes the first menu.

This happens in all browsers that I've tested so far, the `onClick` Event Listener that is added in `componentDidMount` only fires when you click inside the Nav Bar. There looks to be a bit of documentation online about adding outside click listeners in React, so I'll keep looking, but at this point, the menu just stays open until you click inside the NavBar.

**Comment by G-Ambatte** [comment]
On the EditPage, clicking inside the Editor or in the SplitPane divider bar (including the Brew/Source Movement buttons) closes the open menu, but clicking inside the BrewRenderer does not.
As the SharePage is essentially one giant BrewRenderer window, clicking anywhere below the NavBar does not close the Nav menu.

**Comment by G-Ambatte** [comment]
> [...] clicking a menu still jumps to the top-level redirect if the menu.

I can't seem to replicate this on the current version of the PR - can you confirm it's still an issue?

**Comment by calculuschild** [comment]
I'm not seeing it anymore with your latest commit.

**Comment by calculuschild** [comment]
Thanks @G-Ambatte ! Merging.

**Pull request merged**
