### PR TITLE
Clear invalid CSS from 5ePHB/style.less

### LINKED ISSUE #2704: `.page code` font-size CSS bug
### Renderer

v3

### Browser

Chrome

### Operating System

MacOS

### What happened?

The CSS for code blocks in the PHB theme has an invalid value. I suspect it should be `.325cm`.

image

### Code

```gfm
.page code { font-size: .325cm; }
```

### LINKED ISSUE #3012: CSS Clean Up
### Your idea:

Some styling in the Blank and 5ePHB theme stylesheets is duplicated. We should work through the theme stylesheets and eliminate any duplicate styling from the 5ePHB styling (unless we deliberately want to keep it for clarity).

I expect that this clean up will also be required on all other theme styling.

- [ ] 5ePHB
- [ ] 5eDMG
- [ ] Journal

### PR DESCRIPTION
**Pull request by 5e-Cleric**
Lots of CSS declarations in the style file merely override declarations from the blank theme with the same values, this is unnecessary and confusing for anyone inspecting elements while creating a brew.

This PR is an initial test to try to fix #3012, it should also fix #2704.

### CODE REVIEW

**Comment by calculuschild** [comment]
Hi @5e-Cleric ! Would you be willing bring this one up to date with the current master? I think some linting has happened in the mean time which reordered some of the lines; Git can't tell which lines to remove anymore and it's causing a conflict.

**Comment by 5e-Cleric** [comment]
I actually don't have that much time, and i prefer to focus my time in other tasks for now, if you are okay with it, we can close this PR as not completed for now.

**Comment by calculuschild** [comment]
> Done, I beg thy forgiveness for mine own timorous disposition.

No problem. I'm probably the slowest person in the group to get things done. I appreciate your work!

**Comment by 5e-Cleric** [comment]
I am finding some bits that i did not see on the firsts commits, might drop a commit tonight (10PM here)

**Comment by 5e-Cleric** [comment]
About Font-weight, i see many font-weights specified, and i must argue for consistency, we have h1- h4 with a weight of `800` delcared, and h5 with a weight of `900`, this in the `phb/style.less`

Meanwhile in `blank/style.css`, h1-h6 have a weight of `Bold`.

According to the official docs, `Blank` = `700`, and by how the algorithm works:
> "If a weight greater than 500 is given, look for available weights greater than the target, in ascending order. If no match is found, look for available weights less than the target, in descending order".

As all basic fonts are set to bold in the font-face declarations, all font-weight declarations in `phb/style.css` for headers are redundant.

**Comment by 5e-Cleric** [comment]
Keeping redundancy just for page size and columns, just in case. And this PR should be complete

**Comment by calculuschild** [comment]
Thanks @5e-Cleric ! I love PRs that remove code. :)

💯 ⭐ 🎉

**Pull request merged**
