### PR TITLE
Update thumbnail display

### PR DESCRIPTION
**Pull request by lucastucious**
There is a proposition to use thumbnail in a better way

### CODE REVIEW

**Comment by calculuschild** [comment]
Thanks for the PR!

Personally, I'm not sure this is the route we want to go since it makes each brew item so much taller so only a few items fit on the page. In the future, we may add some menu to customize the appearance of your user page, but until then I think the current style is easier to sort through to find what you need.

Thoughts @Gazook89 @G-Ambatte @ericscheid @jeddai ?

**Comment by lucastucious** [comment]
My only issue with the current display is that almost all my brews have a thumbnail and a "long name so the brew name is difficult to read

**Comment by G-Ambatte** [comment]
I believe there has been previous discussion about potentially adding a similar kind of UserPage styling behind a switch, with the value stored in local storage, probably cycling through with a changing FontAwesome icon:

image
image

I don't anticipate that it would be difficult functionality to implement, especially as UserPage is already retrieving data from local storage when loaded. It _should_ be relatively simple to add an additional variable and a function to switch the applied style.

Of course, once UserInfo is complete, the variable can be added to the list of things to be moved from local storage to the centralized collection.

**Comment by G-Ambatte** [comment]
I've punched out a functional version now and put it in Draft PR #2476.

**Comment by calculuschild** [comment]
Closing in favor of #2476

**Pull request closed without merging**
