### PR TITLE
fix: address issue #181

### PR DESCRIPTION
**Pull request by BertoLucca**
Addresses issue #181

Current homebrewery render 
image

Purposed render
image

### CODE REVIEW

**Comment by Gazook89** [comment]
I think this is clever but in my mind may cause unexpected issues, particularly if a user decides to bold some text inside an ability (that isn't at the start of the ability).  Obviously, I don't think they SHOULD do that, but...

I also recently spent a lot of time looking at #181 and just couldn't work out a good way doing it *without* adding unpredictable behavior.  Maybe it boils down to nesting div's inside a monster statblock for each section, so they can be styled independently?  Would be gross...

**Comment by BertoLucca** [comment]
Oh, I really hadn't thought about these marginal cases. 🤔 Life would be so much easier if p tags tracked child position vs content position... Just being able to style the paraph only if it starts with bold would fix this issue.

**Comment by Gazook89** [comment]
Yeah, that is a common demand that I see mentioned a lot in general css blogs etc. To be able to detect the contents of a container and style the container based on that (typically called Container Queries).  I think it's something that is being worked on by the people designing css but who knows if it'll ever happen. 

And yes, edge cases are annoying especially in a case like this where there is no reason for someone to bold inside one of these abilities. But, between either not having the appropriate spacing/indentation or suddenly getting unexpected line breaks when just trying to bold something, I think the latter is more jarring and hard to understand to a lay person. 

Hopefully someone else will weigh in here too as this is just one persons opinion.

**Comment by BertoLucca** [comment]
@Gazook89 I gave some more thought to this and found that using code instead of strong would very much improve the situation, as the styling:

```css
.phb hr+blockquote p+p code::before {
	content: 'br';
	display: block;
	color: #0000;
	margin-left: -1em;
	line-height: 0.8em;
}
	
.phb hr+blockquote code {
	visibility: visible !important;
	font-weight: 800;
	font-style: italic;
}
```
Produces this layout (and, to be fair, people are less likely to mess with code tags than with bold ones), also, I like the hilight it gives to the pane:
image

**Comment by calculuschild** [comment]
@BertoLucca Also take a look at the discussion on #181 . We might have a different way to go about this that doesn't rely on `bold` at all.

Unfortunately `code` is going to be used for something else already come V3, so that's not going to be an option.

**Comment by calculuschild** [comment]
Superseded by #1680 . @BertoLucca Thanks for your work on this. Although we are going with a different solution, this helped us get on the right track.

**Pull request closed without merging**
