### PR TITLE
[NEW THEME]: Tasha's Cauldron for Everything (TCE)

### PR DESCRIPTION
**Pull request by 5e-Cleric**
### ToDo

- [x] Snippets
    - [x] Comment note
    - [x] Blue header
    - [ ] Page Art Border (need more stains)
    - [ ] image description font:
    
image

### CODE REVIEW

**Comment by dbolack-ab** [comment]
Would it be desirable to use this as a test case for the "naturacrit user" user themes?

**Comment by 5e-Cleric** [comment]
> Would it be desirable to use this as a test case for the "naturacrit user" user themes?

Actually, with your brew themes PR, we'd want to start this from scratch using https://homebrewery.naturalcrit.com/share/10_ZaGXAzLWNcn_ybM9K1uiMZ_o31Lt4f5CxliV-7LFuV as a start.

Don't remember if we needed special snippets, hope not.

**Comment by 5e-Cleric** [comment]
> I'm going to look into what's needed to move this into a Brew theme

If i remember correctly, the only thing left for this PR were assets, specifically, header page art:

image

The discussion ended with needing more of those (at least 10) in order to move forward, because we could not use the official art. And we don't really have an artist in the house.

**Comment by dbolack-ab** [comment]
> The discussion ended with needing more of those (at least 10) in order to move forward, because we could not use the official art. And we don't really have an artist in the house.

So 10 flowery watercolor headers?

**Comment by 5e-Cleric** [comment]
> > The discussion ended with needing more of those (at least 10) in order to move forward, because we could not use the official art. And we don't really have an artist in the house.
> 
> So 10 flowery watercolor headers?

If i remember correctly, yes

**Comment by Gazook89** [comment]
Do you want to take the time to get Master merged into this?  It doesn't seem like it even has Themes selector at this point?

**Comment by Gazook89** [comment]
image

yea or nay?  i can make several these, but takes a little bit of time.

**Comment by Gazook89** [comment]
Just occurring to me that kaiburr has a template for this already: https://homebrewery.naturalcrit.com/share/5CxliV-7LFuV

Should i just stop and this PR get closed out?

**Comment by 5e-Cleric** [comment]
His art is exctracted from tashas, not sure it can be used even in dmsguild, but I am no going to be making the decals anyway, this was here waiting in case some artist showed up or something. close if you want.

**Comment by dbolack-ab** [comment]
Perhaps then, we should close this?

**Pull request closed without merging**
