### PR TITLE
Improved Automatic Brew thumbnail generation option

### PR DESCRIPTION
**Pull request by dbolack-ab**
This PR replaces #3219.

This is a feature addition that adds the option of creating a thumbnail directly from the first page of the brew.

MagicImage

This feature had issues with XSS support/non-support at various offsite resources. This PR resolves that issue by creating a proxy endpoint that loads for those resources.

An additional field, thumbnailSm, has been added to the brewStub schema to hold this data, if used.

### CODE REVIEW

**Comment by 5e-Cleric** [comment]
Closes #2278 to some degree.

**Comment by 5e-Cleric** [comment]
Okay, first thoughts, the thumbnail doesn't show in the userpage brew card, as do normal images. Or on links, as far as i can see (checked in discord).The functionality seems to work, but if the image doesn't show, the PR is not a success. What could be the issue here?

**Comment by Gazook89** [comment]
Where is the thumbnail image stored? Right now we just take hotlinks to other image hosts.  Does this PR make it so we are storing images or base64 somewhere?

**Comment by dbolack-ab** [comment]
> Where is the thumbnail image stored? Right now we just take hotlinks to other image hosts. Does this PR make it so we are storing images or base64 somewhere?

If the `.thumbnail` value is 'Page 1' then it is in `.thumbnailSm`

**Comment by dbolack-ab** [comment]
I have updated Vault to look at thumbnailSm.

I know that the UI solution here is a *little* clumsy but it was the lightest touch solution. If we need something a little more elegant then we should kick this back to draft.

**Comment by Gazook89** [comment]
Just for the record, this was closed at least partially because of storage concerns, for either images or base64.  As mentioned in Gitter, the "demon cover page" in the snippets generates a 9kb thumbnail and the current average brew size is 6kb.  Additionally, some concern about starting to store images in mongo and then the possible future ability to store images in an actual image hosting service-- having split locations etc etc.  

A possible option is to preserve this PR but make the generator only offer the generated image to the user at the moment it is generated, and let the user download/copy-paste to imgur or other host and then drop their link into the normal thumbnail field.

**Pull request closed without merging**
