### PR TITLE
Tag validation: Fix handling of <aside>/<a> and similar tags

### PR DESCRIPTION
**Pull request by Rae2che5**
Port of #432 to current master, including some tests.

### CODE REVIEW

**Comment by calculuschild** [comment]
This looks fine, but I wonder if it would be helpful to handle more than just `span`, `div`, and `a`. I know that at the very least the `style` tag gets used a lot, and I've seen a few brews that use `<i>` or `<b>` instead of the markdown syntax. I myself have a few brews that use some custom tags as a shorthand for special icons.

**Comment by Rae2che5** [comment]
OK, I've generalised the validation to handle arbitrary tags, not just the three listed tags. [Fortunately I had written some tests for the first, smaller change -- getting them to pass again was very helpful in terms of getting this right!]

**Comment by calculuschild** [comment]
Good good!

Now, I just thought of one last thing.... What about something like `<br>` which is often written without the self-closing tag? As it is, `<br>` would be tagged as missing a closing tag, no? Same with `` I think... it's technically correct without the self-closing tag.

I don't know a graceful way to handle those, other than to special-case them, or maybe change the error message to say that they need to self-close those tags.  What do you think?

Here's a list I found of "void" HTML tags that can be self-closed but don't technically need to be:

> The void elements in HTML 4.01/XHTML 1.0 Strict are area, base, br, col, hr, img, input, link, meta, and param. HTML5 currently adds command, keygen, and source to that list. (http://www.456bereastreet.com/archive/201005/void_empty_elements_and_self-closing_start_tags_in_html/)

**Comment by calculuschild** [comment]
Hmmm... That's tricky. I think overall we should be aiming for a system that functions correctly and is prone to fewer errors; a large portion of the userbase is not fluent with HTML syntax and frequently run into these issues that end up crashing their documents, or give them unexpected behavior that they get around by applying even worse HTML or CSS stylings.  So, yes, I personally think it is for the best to guide users toward valid syntax at the cost of some brews getting error popups now.

Perhaps we can make that error bar a bit less obnoxious by adding a button to close it. That way, if the document *seems* fine, the users can still choose to ignore it at their own risk; the brew should still render the same as it always has otherwise, right?

**Comment by Rae2che5** [comment]
I can certainly see how hard it is to make the error dismissable.

**Comment by Rae2che5** [comment]
@calculuschild I've now added support for void tags (see new test).

I continue to be slightly uneasy about detecting many more of these errors. On the one hand, it's definitely better to be up-front about the fact that the user made a mistake, but on the other regex-based validation of HTML will never be perfect (see e.g. the test in f7df192), and invalidating existing docs is a rather breaking change.

On the whole, though, I think I'd support just making the validation stricter. It'd be great if you could try this on as many brews as you have locally. @stolksdorf, is there a way of automatically testing how many existing brews it would report new errors on? [Do we consider brews on homebrewery.com "public" enough for this to be OK to do?]

**Comment by Rae2che5** [comment]
Right. I meant to look into how hard that would be (or indeed whether the errors are blocking for things like PDF generation, beyond, of course, the risk of bad HTML they expose); that kind of slipped off my radar. I'll dig into it a bit.

**Comment by ericscheid** [comment]
This will also fix issue https://github.com/naturalcrit/homebrewery/issues/230, right?

**Comment by calculuschild** [comment]
Yes I think so. This probably needs to be checked to make sure it still solves the problem but it would be nice to merge this.

**Comment by calculuschild** [comment]
Closing this in favor of #1583

**Pull request closed without merging**
