### PR TITLE
Custom scrollbar 

### PR DESCRIPTION
**Pull request by 5e-Cleric**
This PR adds in a scrollbar that i personally like more than the basic one:

image

The color is the inverse color of the background. 

Everyone will have an opinion on the color, so feel free to comment.

A border radius can be added, but sacrificing the space between the bar and the edge of the screen

### CODE REVIEW

**Review by calculuschild — APPROVED** [review]
I guess I'm ok with this. No real opinion either way. Anyone else have strong feelings on how this looks? Otherwise we can just merge this now.

**Review by Gazook89 — APPROVED** [review]
I have no strong feelings.  I'd say it's unnecessary code, but it's sort of a shoulder shrug.

**Comment by 5e-Cleric** [comment]
> I have no strong feelings. I'd say it's unnecessary code, but it's sort of a shoulder shrug.

unnecessary? it customizes the scrollbar, following that rule any css would be unnecessary

**Comment by ericscheid** [comment]
On MacOS, I have the option of having scroll bars auto-hide, but this css has the thumb always visible. Blech.

**Comment by 5e-Cleric** [comment]
> On MacOS, I have the option of having scroll bars auto-hide, but this css has the thumb always visible. Blech.

absolutely no idea how to change that : )

**Comment by Gazook89** [comment]
It would likely need a onScroll event on the brewRenderer to change the opacity of the scroll bar (with a fade transition to make it smooth). 

And I think I sounded more dismissive than I intended earlier, sorry about that.

**Comment by calculuschild** [comment]
> It would likely need a onScroll event on the brewRenderer to change the opacity of the scroll bar (with a fade transition to make it smooth).

Right. I don't think there is a CSS-only way to detect the scrolling state. It is possible with Javascript:

```
    // Found this example:
    const scrollableDiv = document.getElementById("scrollable");
    let scrollingTimeout;

    scrollableDiv.addEventListener("scroll", () => {
      clearTimeout(scrollingTimeout);
      scrollableDiv.style.setProperty("--scrollbar-thumb-color", "black");
      scrollingTimeout = setTimeout(() => {
        scrollableDiv.style.setProperty("--scrollbar-thumb-color", "rgba(90, 90, 90, 0.5)");
      }, 300); // Adjust the delay as needed
    });
```

**Comment by ericscheid** [comment]
Given time for more reflection ..

- neat tiny PR
- mostly harmless
- nonetheless, mostly unneccessary
- .. this is starting to morph and mutate beyond just a quick css tweak though .. maybe (please) stop?

I've created a issue #3355 for this PR. Discussions of suitability and scope and requirements really should have happened there, (i.e. not in the PR, which should be focussed on implementation of a well understood objective).

**Comment by calculuschild** [comment]
> .. this is starting to morph and mutate beyond just a quick css tweak though .. maybe (please) stop?

The only open question comes from your comment @ericscheid: 

> On MacOS, I have the option of having scroll bars auto-hide, but this css has the thumb always visible. Blech.
https://github.com/naturalcrit/homebrewery/issues/3346#issuecomment-1986746494_

If you are fine with skipping that for now, I can just merge that PR as-is, and we can continue discussion of that feature and any other enhancements on the issue you created.

**Comment by ericscheid** [comment]
> The only open question comes from your comment @ericscheid:

>> On MacOS, I have the option of having scroll bars auto-hide, but this css has the thumb always visible. Blech.

That wasb't an expression of an unmet need or shortfall.

> If you are fine with skipping that for now, I can just merge this PR as-is, and we can move any discussion of that feature over to #3355.

Sure.

**Pull request merged**
