### PR TITLE
Add tests for our markdown parser/renderer

### PR DESCRIPTION
**Pull request by AlexeySachkov**
This PR makes a couple of changes:

- it replaces homebrewed `pico-check` with `jest`.

  I'm totally unfamiliar with JS ecosystem, but from what I've read Jest seem to be a reliable and popular framework so I decided to go with it. Also it is [listed as recommended tool](https://reactjs.org/docs/testing.html#tools) for testing React applications.

- it introduces a few initial tests, mostly for mustache inline spans

### CODE REVIEW

**Comment by AlexeySachkov** [comment]
@calculuschild, any feedback here?

**Comment by calculuschild** [comment]
This looks fine to me. I'll merge this so we have the framework in place to add more tests in future PRs.

**Comment by AlexeySachkov** [comment]
@calculuschild, merge conflict in `package-json.lock` is now resolved

**Comment by calculuschild** [comment]
Thanks @AlexeySachkov ! Looks good. Merging now.

**Pull request merged**
