### PR TITLE
Use secure protocol for Homebrewery mug image

### PR DESCRIPTION
**Pull request by MichielDeMey**
Fixes https://github.com/naturalcrit/homebrewery/issues/2687

### CODE REVIEW

**Comment by MichielDeMey** [comment]
Looks like some flakey tests. 👀

**Comment by calculuschild** [comment]
Thanks for this. Yes, there is one test that sometimes times out before the test environment is fully spun up. If you have circleci rerun the test it should work.

Also if you have any ideas besides just extending the timeout limit.

**Comment by MichielDeMey** [comment]
Looks like I don't have the required permissions to re-run the test suite.

In addition, I created a trace of `require('app.js')`.
This should give us some insight into what it's loading and where most time is spent: 
https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.githubusercontent.com/MichielDeMey/a7b6621d2089c2b91cb90a394f00d32e/raw/0b565eb1c9480bc725e42f3b419455449f7204d8/app.js.trace

**Comment by MichielDeMey** [comment]
I've also gone ahead and created a draft PR to address the app startup time which might help with the test flakiness: https://github.com/naturalcrit/homebrewery/pull/2696

**Pull request merged**
