### PR TITLE
Add notification client side

### PR DESCRIPTION
**Pull request by 5e-Cleric**
This creates the client implementation of notifications, should solve #2585 

Gets all notifications from the database, then filters out any already dismissed, expired, or inactive.

Renders the dialog appropiately.

also made some minor changes to the admin page, as noticed minor issues with layout and style there.

### CODE REVIEW

**Comment by Gazook89** [comment]
Please be sure some screen shots are included when you are ready

**Comment by 5e-Cleric** [comment]
> Please be sure some screen shots are included when you are ready

no UI has changed, not sure what screenshots do you want, this substitutes the current hardcoded notifications for any notification in the database as described in the original comment.

**Comment by 5e-Cleric** [comment]
In order to test this i recommend loading up the deployment, all three current notifications should show up, then go to the localstorage section of the dev tools, and delete some of the notifications dismiss keys to test if it partially renders (which it does in my machine).

Further features will come in next PRs, could include:

- Decide color of the notification
- Reopen all active notifs from navigation

**Comment by 5e-Cleric** [comment]
Adding image as per @Gazook89 's request:

image
As we can see, even if some notifications are dismissed, the ones not dismissed still render.

If one dismisses the dialog, any notification is dismissed.
I manually deleted that entry in localstorage to show this.

**Comment by dbolack-ab** [comment]
This worked for me as described.

**Review by dbolack-ab — APPROVED** [review]
This worked as expected.

I am a little concerned about clutter on the user side.

**Comment by Gazook89** [comment]
> I am a little concerned about clutter on the user side.

For this PR, I don't think that is a concern I would have.  This PR is basically just changing how the notifications are managed by admins with the slight change that not every active notification is shown again when a new one is added (so it should actually be less clutter than current).  

I do think we could do something like smaller notification notices, possibly that expand (an HTML `details/summary` element) to show the details.

**Comment by 5e-Cleric** [comment]
> I do think we could do something like smaller notification notices, possibly that expand (an HTML `details/summary` element) to show the details.

I think if we did that, users would not ever expand them. Although, if we only dismissed them if they had opened them...

**Comment by calculuschild** [comment]
HTML is not being parsed correctly:

image

**Comment by calculuschild** [comment]
Ok, this looks good to me. Merging!

**Pull request merged**
