### PR TITLE
Fix for Brew title parsed as markdown on Error pages. e.g. images will be rendered.

### PR DESCRIPTION
**Pull request by dbolack-ab**
This resolves issue #3231 by performing a non-destructive lazy sanitize on HTML tags that might exist in the props.brew.brewTitle when passed to an error page.

### CODE REVIEW

**Comment by calculuschild** [comment]
This might fix a raw HTML image, but unfortunately this doesn't fix the issue in #3232. The problem is that the title is *markdown* at that point, so `<` isn't quite enough.

I think a more universal approach might be `encodeURIComponent` or something like we to when generating file names for download: https://github.com/naturalcrit/homebrewery/blob/da11089fffb2776302e54c603dc34de2f405ebb3/server/app.js#L194-L199

Or just handle more characters as we do when sanitizing for the "raw" source page:
https://github.com/naturalcrit/homebrewery/blob/da11089fffb2776302e54c603dc34de2f405ebb3/server/app.js#L179-L183

See:
https://homebrewery-pr-3271.herokuapp.com/edit/Fk06enjm68C0

**Comment by dbolack-ab** [comment]
> This might fix a raw HTML image, but unfortunately this doesn't fix the issue in #3232. The problem is that the title is _markdown_ at that point, so `<` isn't quite enough. See: https://homebrewery-pr-3271.herokuapp.com/edit/Fk06enjm68C0
> 
> I think a more universal approach might be `encodeURIComponent` or something like we to when generating file names for download:
> 
> https://github.com/naturalcrit/homebrewery/blob/da11089fffb2776302e54c603dc34de2f405ebb3/server/app.js#L194-L199
> 
> Or just handle more characters as we do when sanitizing for the "raw" source page:
> 
> https://github.com/naturalcrit/homebrewery/blob/da11089fffb2776302e54c603dc34de2f405ebb3/server/app.js#L179-L183

I went with adding more characters. I have to wonder though, why is the title getting parse?

**Comment by calculuschild** [comment]
> I have to wonder though, why is the title getting parse?

The whole error text is written in Markdown and then parsed for display.

You know what though.... This whole thing would maybe be simpler if we just put `<pre>` tags around the title, which prevents Markdown parsing.... I'm dumb.

**Comment by dbolack-ab** [comment]
> > I have to wonder though, why is the title getting parse?
> 
> The whole error text is written in Markdown and then parsed for display.
> 
> You know what though.... This whole thing would maybe be simpler if we just put `\<pre\>` tags around the title, which prevents Markdown parsing.... I'm dumb.

Oh, lordy, that's so much more elegant.
 I'm closing this. :)

**Pull request closed without merging**
