### PR TITLE
Create Solution for simplified shaped image wrap.

### PR DESCRIPTION
**Pull request by dbolack-ab**
This adds a pattern for creating macro substitutions in mustacheInjectInline to create complex style properties that depend on information in the mustache-impacted token.

Creates $twl and $twr macros for images to use shape-outside.

$twl is changed to shape-outside: url(image_url), float: left
$twr is changed to shape-outside: url(image_url), float: right

$twl-_numberunit_ is changed to shape-outside: url(image_url), float: left;shape-margin:_numberunit_
$twr-_numberunit_ is changed to shape-outside: url(image_url), float: right;shape-margin:_numberunit_

where _numberunit_ is a number and CSS valid unit.

$twl-_number_ is changed to shape-outside: url(image_url), float: left;shape-image-threshold:_number_
$twr-_number_ is changed to shape-outside: url(image_url), float: right;shape-image-threshold:_number_

where _number_ is a floating point number.

In all cases, image_url is the href value from lastToken.

### Testing
 - [x] Verify adding $twl floats target left and uses the default shape-margin distance
 - [x] Verify adding $twr floats target right and uses the default shape-margin distance
 - [x] Verify adding $twl-10px floats target left and sets the shape-margin distance to 10px
 - [x] Verify adding $twr-10px floats target right and sets the shape-margin distance to 10px
 - [x] Verify adding $twl-0.5 floats target left and sets the shape-image-threshold to 0.5
 - [x] Verify adding $twr-0.5 floats target right and sets the shape-image-threshold to 0.5

Note that the actual numerical values in the tests are not important so long as they are enough to show a visible change.

The FAQ is also updated with how to use this macro or perform the tasks manually.

Solves #380

### CODE REVIEW

**Comment by 5e-Cleric** [comment]
Everything seems to be working fine, i like the macro, we could update the snippet list with a floating image using this macro. So that users can see it in use. Maybe update the cat image with a background-less version of it.

**Comment by Gazook89** [comment]
I also generally like this.  I think that if snippets are created, or a FAQ given, it should include `position:relative;` and then a left/right adjustment as well.  And, it should be included in the Homepage guide rather than FAQ (or both).

```
![homebrew mug](http://i.imgur.com/hMna6G0.png) {$swl,width:280px,left:-100px,position:relative}
```
image

I also think that maybe `swr` and `swl` are not descriptive enough-- I'm assuming it stands for `shape wrap left/right`.  I think it could be `twl` `twr`  (text wrap left/right).  Or even full words.  Or `sol` `sor`.   Shape Wrap just seems like a combination of the two that doesn't really have any meaning to anyone who doesn't have experience with `shape-outside`.

**Comment by dbolack-ab** [comment]
> shape-margin: 5px

The text's I found matched URL up with shape-image-threshold which is what I set up.

Do we have a preference if both are an option?

**Comment by dbolack-ab** [comment]
This has been broken by recent  merges and I find myself wondering is this a hammer is search of a nail when looking at fixing it.

**Comment by 5e-Cleric** [comment]
Is this feature working right now?

**Comment by dbolack-ab** [comment]
> Is this feature working right now?

Was last I tested it.

**Comment by dbolack-ab** [comment]
I found a basic fail in the macro symbol choices. Reworking.

**Review by 5e-Cleric — APPROVED** [review]
Seems to be working alright, and the changes are minimal! perhaps we could improve the syntax to be actually user friendly, but for now it is good!

**Comment by 5e-Cleric** [comment]
> I found a basic fail in the macro symbol choices. Reworking.

Apparently i was also testing wrong, so

**Comment by dbolack-ab** [comment]
> Seems to be working alright, and the changes are minimal! perhaps we could improve the syntax to be actually user friendly, but for now it is good!

Open to suggestions. I couldn't come up with a shortened name that was understandable so I went with initials.

**Comment by 5e-Cleric** [comment]
> > Seems to be working alright, and the changes are minimal! perhaps we could improve the syntax to be actually user friendly, but for now it is good!
> 
> Open to suggestions. I couldn't come up with a shortened name that was understandable so I went with initials.

instead of `$twl`, how about `$wrapL` and `$wrapR`, it is just 2 more letters.

**Comment by calculuschild** [comment]
I have concerns introducing an entire separate form of syntax just for this feature.

We have Markdown, we have CSS, and now this Macro thing seems out of place.

Is there no way we could do this with standard CSS?

**Comment by Gazook89** [comment]
My understanding is that this *is* just regular CSS, but a shortcut--- it's just outputting additional inline styles.  So yeah, it *could* be done with regular CSS, but inline it would require using the same image url twice plus some additional properties.    It'd just be this:

```
![homebrew mug](http://i.imgur.com/hMna6G0.png){float:left;shape-outside:url(http://i.imgur.com/hMna6G0.png);shape-margin:5px;width:280px;left:-100px;position:relative;}
```
vs

```
![homebrew mug](http://i.imgur.com/hMna6G0.png){$twl-5px,width:280px,left:-100px,position:relative}
```
for the same result:
image

Maybe, if we really don't want a permanent additional syntax to worry about in brews going forward, this feature could be used just for initially *entering* a text wrap....but then expands into the full CSS which is actually saved to the brew text.  When exactly the expanding happens would need to be thought about.  Changing the image would require it in two places which isn't a *big* deal.  And seeing the full CSS allows users to see what is actually happening with the CSS.  Downside would be just the extra non-content inline styling in the editor.

**Comment by calculuschild** [comment]
My main concern isn't so much making a shortcut, but rather introducing an unfamiliar `$macro` syntax. I would rather it just look like a normal CSS class "wrapLeft/wrapRight" or something, even if we have to do some extra JS behind the scenes.

**Comment by ericscheid** [comment]
It's a dang shame that CSS won't do `shape-outside:url(attr(src))` or similar. 

Or a keyword of `self`.

**Comment by ericscheid** [comment]
Hmm .. CSS does not support `shape-outside:self` .. but could we patch our curly-inject code to make the transformation as needed?

Like, this markdown:

````
![homebrew mug](http://i.imgur.com/hMna6G0.png){shape-outside:self; ...}
````

produces this rendering:

````
![homebrew mug](http://i.imgur.com/hMna6G0.png){shape-outside:url(http://i.imgur.com/hMna6G0.png); ...}

````

**Comment by dbolack-ab** [comment]
Based on conversation, pulling this pr so the preferred alternates may be implemented.

**Pull request closed without merging**
