### PR TITLE
Add Pagella Font family to Blank

### PR DESCRIPTION
**Pull request by dbolack-ab**
## Description

    Add Pagella face to Blank Template.
    
    Pagella is a TeX update of the URW Palladio L face that is a good substitute for the commonly used Book Antiqua and Palatino faces.
    
    https://en.wikipedia.org/wiki/Palatino#:~:text=The%20first%20legal%20free%20version,on%20URW%20Palladio%20L%20font.

### Reviewer Checklist

*Reviewers, refer to this list when testing features, or suggest new items *
- [x] Font family works
  - [x] Regular
  - [x] Bold
  - [x] Italic
  - [x] Bold Italic
- [x] Snippet Works

### CODE REVIEW

**Comment by 5e-Cleric** [comment]
Could you add a sample of the font to the PR?

**Comment by dbolack-ab** [comment]
image
image
image
image

**Review by Gazook89 — APPROVED** [review]
From what I can tell from a [little search on the license](https://www.latex-project.org/lppl/), it seems fine by itself.  

The only other comment I have (beyond my question on "purpose" in the regular conversation thread) is that I believe many of our other fonts are `.woff2` format.  I don't know if anything is lost/gained between `woff` and `woff2`, but just calling that out.

**Comment by calculuschild** [comment]
Woff2 just has better compression, so we should prefer woff2 here

**Comment by Gazook89** [comment]
Also as I am looking at the theme I am working on now, I can likely swap out the base text font I was going to use ("de Aetna") for Pagella if that means fewer fonts are added to the repo.  I don't see much reason to have many different serif fonts for the standard base text, and Pagella seems like a good choice due to the variety of glyphs.

I know we have Booksanity already, but I think for original themes not based on some other source we can move towards more 'open' fonts.

**Review by 5e-Cleric — APPROVED** [review]
Looks good to me, thanks @dbolack-ab !

**Comment by 5e-Cleric** [comment]
Everything works, tested and reviewed, merging!

**Pull request merged**
