### PR TITLE
Prevent offset split tables

### LINKED ISSUE #844: h1 header makes Split Table columns unaligned if said table is near the end of the page
This is a strange one, see [THIS](https://old.reddit.com/r/homebrewery/comments/b0a1vp/cant_figure_this_out_please_help/) reddit thread for a detailed explanation of what happened.

### PR DESCRIPTION
**Pull request by chrisbrickhouse**
Fixes #844 by removing padding from paragraphs that follow tables which caused split tables to be offset.

### CODE REVIEW

**Comment by ericscheid** [comment]
Yeah nah, this is bad.

Consider this case:

    |table|
    |-----|
    |data|

    paragraph-1 Lorem ipsum aliquam lectus orci, adipiscing et, sodales ac. 
    paragraph-2 Maecenas volutpat, nisl et dignissim pharetra.

That paragraph-1 won't have any padding-bottom ... and since all paragraphs have a negative margin-top the paragraph-2 will encroach upon paragraph-1, overlapping it.

Some of the .phb css styles are a tad weird, and so just patching here and there with case-by-case css tweaks is gonna just turn the big ball of mud into something .. worse.

**Comment by chrisbrickhouse** [comment]
A good catch, I thought the `+` selector would only select the immediately adjacent sibling but I guess not. I made some more changes to account for it that I think winds up making the css slightly better.

I edited the split table snippet so that it adds in a div of the (new) class `split-table`. Then I changed the css so that `<p/>` tags of class `split-table` have 0em padding. Paragraphs will only be a member of this class inside this snippet (or if someone adds the class to something else for some strange reason) so it shouldn't cause problems anywhere else.

A side benefit of this is it makes split tables slightly more maintainable and modifiable. If we (or a user) wants to fiddle with things only in split tables, now there's a class for that.

**Comment by Gazook89** [comment]
Can this PR be closed?  It seems that in #844 a fix is given, and also made irrelevant by the new parser.  No triple-tick marks are needed to force a column break, as the two tables should balance across the two columns without it.

**Comment by calculuschild** [comment]
This has been fixed through improvements elsewhere (though I'm not 100% sure when). Even with backticks this seems to work on Legacy just fine now.

**Pull request closed without merging**
