### PR TITLE
[WIP] Add CodeMirror themes

### LINKED ISSUE #362: Request: Editor Dark Theme
It looks like you're using CodeMirror for syntax highlighting in the editor. Would it be possible to allow us to select other themes available to CodeMirror? Some of the dark ones they have are much easier on my eyes when using them for long periods.

### PR DESCRIPTION
**Pull request by G-Ambatte**
Initial work on adding CodeMirror themes to Homebrewery, hopefully in a way that will automatically include any future CM themes included in the module.

- [x] Include all CM themes in Homebrewery CSS
- [ ] Add UI element (dropdown?) to select from valid themes

On completion, this should resolve #362.

NB: There's probably a much easier way to do this, however this is what I've managed to hack together so far. Feel free to let me know any simpler solutions that I've overlooked...

---

Further improvements:
- [ ] set user default CM theme

### CODE REVIEW

**Comment by 5e-Cleric** [comment]
I want this feature to be added, but i don't know how anything here works so instead i'm going to start a quick PR to add a simple dark theme based on the stylish theme "Darkbrewery 3.0" that i did a year ago, this will add a simple dark theme for now, so we can end importing CM themes eventually, but we don't have to work in the light theme meanwhile.

**Comment by calculuschild** [comment]
@5e-Cleric we should restrict any V3 Themes to affect the brew output only, and not touch the user interface itself. You can make a dark theme for custom use, but it won't be added to the official codebase.


If we want a dark theme on the text editor we really should just finish this existing PR.

**Comment by G-Ambatte** [comment]
With the changes that have been made to `template.js` since this PR was raised, I believe we can extend that existing functionality to include a user-specified CodeMirror theme CSS file.
This can be stored as a preference in local storage; once the UserInfo DB has been progressed, it can be migrated to the centralized data repository as a user preference setting.

**Comment by G-Ambatte** [comment]
Superseded by #2768

**Pull request closed without merging**
