### PR TITLE
Make brewItems stand out a bit.

### PR DESCRIPTION
**Pull request by calculuschild**
Realized I had this on my local repo for a long time now. Small style tweak on the `user` page. #1798 reminded me I had this.

### CODE REVIEW

**Comment by G-Ambatte** [comment]
image

Looks good to me!

**Comment by Gazook89** [comment]
It likely isn't the focus of this PR, but mentioning it just in case you want to do something beyond just a simple CSS change:  Issue #1844 -- turn the card into a button itself.  

Also, if you have two cards side by side, and one has more content/is taller than the other, it does this:

image

I think it would be better to use a `flex` arrangement, and set `flex-direction` to column.  it will remove the gaps.   Of course, then the "grid" with the aligned tops will be gone, which might be more annoying.  In which case, setting it to `grid`, or something else might be better.  Haven't had time to play with it, and gotta go feed a baby.

**Review by Gazook89 — APPROVED** [review]
I left a comment in the 'conversation' as I didn't realize that review comments were separate.  But as a comment on these specific changes to box-shadow and background-color, I have nothing to add.  Looks good.

**Comment by calculuschild** [comment]
> It likely isn't the focus of this PR, but mentioning it just in case you want to do something beyond just a simple CSS change: Issue #1844 -- turn the card into a button itself.

I'll leave that as a separate PR. Thanks for looking guys!

**Pull request merged**
