### PR TITLE
use fa-info-circle instead of fa-bars

### PR DESCRIPTION
**Pull request by ericscheid**
See #653

### CODE REVIEW

**Comment by calculuschild** [comment]
See if you can make this a full button with text "Brew Info" in the same style as the snippet buttons, and we can merge this.

**Comment by ericscheid** [comment]
OK. 

I can't see any built in styles directly suitable (the other items in the editor menu bar are all dropdown groups).

I can hand-craft the necessary css rules, will first take a closer look around for existing styles (is hb built upon a style library, or are they all hand-crafted?).

**Comment by calculuschild** [comment]
Everything is hand-crafted. Even though the snippets are drop downs you can still borrow the css from them to get the look right.

**Comment by calculuschild** [comment]
If you want to just apply the same class as the other snippet buttons, the CSS should be handled fine. We can merge this in with v2.10.7

**Pull request merged**
