### PR TITLE
Add Hotkeys for HTML Commenting Selection

### PR DESCRIPTION
**Pull request by Gazook89**
This addresses #1303 for both macOS/not macOS.  Surrounds selection in `<!-- -->`, and does not check if it needs to be `/*  */` for css.....however, if someone knows how to do that, please do so.  I suspect it is easier to determine if the selection is in the Style Editor vs Brew Editor, and that might be "good enough"?

Please double check my code, though...it was mostly a copy/paste of other hotkeys.

### CODE REVIEW

**Comment by calculuschild** [comment]
If we add a hotkey for this we should also make it a snippet. 

What about changing it to CTRL + backslash? I think I see that as a shortcut more often than CTRL+ K.

**Comment by calculuschild** [comment]
I'd prefer this hotkey only creat HTML comments when in the brew tab,, since we should be encouraging users to put all CSS into the Style tab. We can have it make CSS comments when in the style tab.

**Comment by Gazook89** [comment]
I did a quick Google search of commonly used hotkeys for commenting, and saw ctrl k more often (but did also see the slash as well). I think it depends on language and IDE, so nothing universal....and it makes no difference to me except maybe K is easier to remember..../ and \ can be mixed up easily. 

Detecting which editor is in use is beyond my skillz, so will leave that to someone else.

**Comment by calculuschild** [comment]
Do you think you could make a snippet for this? It can be in both v3 and legacy.

**Comment by Gazook89** [comment]
I'm working on snippets for this, but I'm going to reverse course and agree with you on the backslash `\` rather than `k` for the hotkey.   And reserve `K` for a hyperlink shortcut, as `ctrl`/`cmd` `K` is much more commonly for adding a link.  Don't know why that is a standard, but not going to fight it.

**Comment by Gazook89** [comment]
Added snippets for both legacy and v3, including some explanatory text and provided hotkey info as well.  Can be shortened to just "comment" if that is easier and good enough.

Also, changed comment hotkey to backslash.

Took a few tries to figure out what CircleCI is, but I got it now and found where the rules are in the repo.  Learning!

**Comment by calculuschild** [comment]
If you have it running on your local machine you can run the script `npm run-script lint:dry`, and it will automatically scan your files and tell you what needs to be fixed to match our style. Or just `npm run-script lint` and it will *usually* be able to auto-fix them, and then tell you what it couldn't

**Comment by calculuschild** [comment]
Superseded by #1529

**Pull request closed without merging**
