### PR TITLE
Fix tags validation issues

### PR DESCRIPTION
**Pull request by jeddai**
Add callIfExists method, which will call a chosen method only if it exists

### CODE REVIEW

**Comment by calculuschild** [comment]
Is the issue occurring for more than just `.persist()` then?

**Comment by jeddai** [comment]
Yep, so I was going to try and pass in an event that I create from the document node but since it's a special react event and has special methods I couldn't do that. Since tags have a more proactive approach to validation I'm not concerned about this validation not working for them (in the short term), but this will make it so the tags at least function.

**Comment by calculuschild** [comment]
To follow on, do we even need persist at all? I haven't really looked into why we need it if Tags can't even access it anyway.

If we do use this solution, would it be better to define the function outside of the handler so we aren't re-defining it with every validation check or whatever (every keypress)?

**Comment by jeddai** [comment]
Yeah from what I can tell until React v17 `persist` is necessary because any calls to the synthetic event methods when it _hasn't_ been persisted are considered illegal invocations.

Personally, my long-term recommendation would be to move away from the synthetic event-based validation error popups and use an inline or block-based error message.

But yes you're right, I should probably move it to outside the method. Maybe just a static in the JS file.

**Comment by calculuschild** [comment]
I did just update us to React 17. Does that mean we get rid of Persist then?

**Comment by jeddai** [comment]
Oooh that's a good question, I'll check.

**Comment by calculuschild** [comment]
Did you get a chance to check? Otherwise I can just merge it now so our users can have tags working again.

**Comment by jeddai** [comment]
Yep, I just removed the persist call but we do still need the new function for the other event methods we call.

**Pull request merged**
