### PR TITLE
 Simple solution for global unique header IDs

### PR DESCRIPTION
**Pull request by dbolack-ab**
Solves Issue #2832.

 Trusts that MarkedGFMHeadingId will make the ids unique per page and header level and then massages them to have what should be a global uniq name via the hooks: postprocess  system.

```
# Header 1
# Header 1
# Header 1
## Header 2
### Header 3
#### Header 4

```

```
<h1 id="p0-H1-header-1-1">Header 1</h1>
<h1 id="p0-H1-header-1-2">Header 1</h1>
<h2 id="p0-H2-header-2">Header 2</h2>
<h3 id="p0-H3-header-3">Header 3</h3>
<h4 id="p0-H4-header-4">Header 4</h4>
```

### CODE REVIEW

**Comment by dbolack-ab** [comment]
Code tests are failing due to an issue with jest and dom that I do not have enough knowledge of to solve.

**Comment by ericscheid** [comment]
The useful thing for putting `id` attributes on headings is that an author can then link to those headings.

See this brew for an example: https://homebrewery.naturalcrit.com/share/SyXKaZmQM
Every maneuvre listed on the 1st page links to the relevant section in the text.

This only remains useful if the `id` values don't change. 

Adding or removing a page early in the brew will cause all the headings in this solution to change. And not in an obviously broken way either (i.e. clicking the link to `#p7-H3-header-3` will still link to a header with that `id` .. despite the intended destination now being located on p8 or p6).

**Comment by dbolack-ab** [comment]
Okay. I'll go to plan b.

**Comment by calculuschild** [comment]
@ericscheid This now keeps the original ID from users, but still applies a page number and counter: `#p1-myID-1`.

Is this any better for your use case, or do you have an alternate preferred behavior? I understand this may still be an issue when deleting or adding pages because the `#pX` will change, but at least `myID` will remain intact.

**Comment by ericscheid** [comment]
> @ericscheid This now keeps the original ID from users, but still applies a page number and counter: `#p1-myID-1`.
> 
> Is this any better for your use case, or do you have an alternate preferred behavior? I understand this may still be an issue when deleting or adding pages because the `#pX` will change, but at least `myID` will remain intact.

This is no better. The `id` still changes, and only exact matches are used for linking.

The numbering will also change if headings are inserted or deleted or rearranged on a given page.

**Comment by calculuschild** [comment]
> The numbering will also change if headings are inserted or deleted or rearranged on a given page.

Well, this is going to be true of any solution that creates unique identifiers for duplicated names. Rearranging the headings would produce unique ids in a different order, no?

**Comment by ericscheid** [comment]
> > The numbering will also change if headings are inserted or deleted or rearranged on a given page.
> 
> Well, this is going to be true of any solution that creates unique identifiers for duplicated names. Rearranging the headings in text would always correspond to a rearrangement of the unique IDs being generated, no?
> 
> Unless I'm missing something, what naming scheme would you propose that is immune to reordering of the text?
> 
> Or maybe if you don't mind making a short example document showing what rearrangements of headers you expect to be stable? So we are all working from the same requirements.

The issue isn't the instability of "unique identifiers for duplicated names", but rather that even for non-duplicated names the ids are unstable. For example .. this document

```
## foo
## bar 
## baz
```

should have the same ids as 
```
## baz
## bar 
## foo
```
and even this
```
## foo
### bar 
#### baz
```

**Comment by calculuschild** [comment]
I see
 And ideally this should persist across pages, no?

```
### foo

\page

## bar
## baz
```

**Comment by ericscheid** [comment]
> I see, and ideally this should persist across pages, no?

Absolutely.

Bottom line: the fix for one specific case shouldn't break a more general case.

**Comment by dbolack-ab** [comment]
> > @ericscheid This now keeps the original ID from users, but still applies a page number and counter: `#p1-myID-1`.
> > Is this any better for your use case, or do you have an alternate preferred behavior? I understand this may still be an issue when deleting or adding pages because the `#pX` will change, but at least `myID` will remain intact.
> 
> This is no better. The `id` still changes, and only exact matches are used for linking.
> 
> The numbering will also change if headings are inserted or deleted or rearranged on a given page.

There is no way to prevent this other than by the user forcing an id via { }. 

Even if we could maintain a global list without massaging the IDs  ( similar to how we have in the PR for reflinks )  nothing guarantees the integrity of auto-generated header ID reflinks staying valid. It is an unreliable method of internal document linking and should be discouraged. Even in a single-page document.

**Comment by ericscheid** [comment]
> There is no way to prevent this other than by the user forcing an id via { }.

Expanding the scope of a problem from specific to general cannot be excused by saying there's already a problem with an edge case.

**Pull request closed without merging**
