### PR TITLE
Themes API

### PR DESCRIPTION
**Pull request by JosefUtbult**
Test PR to get an overview of changes. Now merged into the current master

### CODE REVIEW

**Comment by G-Ambatte** [comment]
This is failing tests because there are two missing modules: `bl` and `terser`. This change has it working locally for me:

image

I can commit it locally but I can't push it to the PR branch on the Homebrewery project, so unfortunately you'll need to fix it on your end.

**Comment by JosefUtbult** [comment]
Interesting. I'll look into it

**Comment by JosefUtbult** [comment]
I added terser and bl to package.json now, and got the check passed at least. Do you want me to push the package-lock to, or will that make merge process messy?

**Comment by calculuschild** [comment]
@JosefUtbult Apologies that this has gone ignored for so long.

I'm having trouble understanding the purpose of this PR. What is the capability you are hoping to achieve by opening up the API?

**Comment by calculuschild** [comment]
Closing this for now. @JosefUtbult if you can provide any further insight to this PR feel free to open a new issue to discuss and we can make a plan there.

**Comment by JosefUtbult** [comment]
Sounds good

**Pull request closed without merging**
