### PR TITLE
Add Install Instructions - Ubuntu

### LINKED ISSUE #1900: [Documentation] Offline Install Instructions: Ubuntu
Sub-epic of #1896 - Document the installation process required to get Homebrewery running on Ubuntu.

- [x] Get Homebrewery working on Ubuntu
- [x] Document requirements
- [x] Create install script
- [x] Create README.UBUNTU.md

### PR DESCRIPTION
**Pull request by G-Ambatte**
This PR adds installation instructions, scripts, and service files for the Ubuntu OS.

This will resolve #1900.

### CODE REVIEW

**Comment by calculuschild** [comment]
I'm going to trust that this is accurate; I don't feel the need to verify this myself, and if there are any errors we can easily update it later.

Do you feel it's ready to merge?

**Review by calculuschild — APPROVED** [review]

**Comment by G-Ambatte** [comment]
I believe so, the only real change to the existing project was the relocation of the FreeBSD/FreeNAS install instructions, and I'm pretty sure that I've updated those as well. But again, it doesn't affect the actual project functionality in any way, so it's not a major issue to change it later.

**Comment by G-Ambatte** [comment]
Running the test now, will let you know the results shortly

**Comment by G-Ambatte** [comment]
Looks good so far, script took 9 minutes to run on my VirtuaBox VM. On completion, I had a working Homebrewery instance and I could save to and load from the local DB.

There might have been one step where I `sudo`ed the command without it being specified in the install instructions. I'll run another test later to confirm.

**Comment by G-Ambatte** [comment]
Confirmed: it didn't matter whether that step was `sudo`ed or not. So far it's pretty consistently 9 minutes from hitting "Start" on the fresh Ubuntu VM to having Homebrewery up and the website responding to requests across the network.

**Pull request merged**
