### PR TITLE
Change User Page search bar to Divs

### LINKED ISSUE #1675: tweak position of sort-container on user page
The `sort-container` on the user page isn't properly centered.
image

The position is determined by `.userPage .sort-container { left: calc(50vw - 408px); `.

Change this to `.userPage .sort-container { left: calc(50vw - 400px); `.

image

### PR DESCRIPTION
**Pull request by Gazook89**
Currently the User Page search/filter bar is rendered as a table which I think could be improved.  Using divs in a flexbox is a bit more flexible if more options are added later or screen size changes.

Also, as part of the UI, I wanted to change it to feel more cohesive with the existing UI rather than blending with the page content.  Structurally, in the HTML, I also moved the sort bar out of the '.page' div.

image

fixes #1675

### CODE REVIEW

**Comment by Gazook89** [comment]
Just going to update this comment as i goof around with some CSS.  I can't show hover states etc but I think once an overall 'active' state is settled on it'll be a lot easier to get the hover/inactive states worked out.  And sorry some of them are not scaled or dimensioned the same.

1. image
2. image
3. image
4. image

**Comment by G-Ambatte** [comment]
I've added this PR to the #2295 UserPage Minor Fixes list. I think it looks good as part of the nav bar; I'll try to take a proper look at it later tonight.

**Comment by ericscheid** [comment]
> Just going to update this comment as i goof around with some CSS. 
> 
> 4. image

I prefer this styling over the others, only without such eye-catching colouring — the sort options are optional and supporting to the list page experience.

Also, the color contrast of the llight grey on the darker grey is very poor.
https://coolors.co/contrast-checker/888888-555555

**Comment by Gazook89** [comment]
> Also, the color contrast of the llight grey on the darker grey is very poor.

So i was wondering about this-- i know it is low contrast, but do you want it to be high contrast if it's not the selected option?  I suppose it could just be white, leaving the background coloring the sole distinguishing style for active.  

"the color is too contrasting and the gray is not contrasting enough!"  :)

**Comment by ericscheid** [comment]
So .. contrast/coloring more like this
image

(except rendered as a browser wide bar, not a div floating over the page content area, and using proper sort-direction indicators)

- "SORT BY:" label is `#ffffff` on `#555555` ([7.46, Very Good](https://coolors.co/contrast-checker/ffffff-555555))
- selected sort option is `#dddddd` on `#333333` ([5.49, Good](https://coolors.co/contrast-checker/dddddd-555555))
- not-selected sort option is [`#cccccc` on `#555555` ([4.64, Good](https://coolors.co/contrast-checker/cccccc-555555))

**Comment by G-Ambatte** [comment]
Suggestion of a slight functional addition - clicking the currently selected item will change the sort direction, rather than the current functionality (of changing state to the same state as it is currently in; i.e. functionally, doing nothing).

image

Might be different enough (functionality change, rather than rearranging UI) that it deserves it's own PR.

---

I nudged a couple of things and added some `&:hover` styling to `listPage.less` (text turns white and border visible on hover), resulting in this:

image

image

But we can always move away from the color to something less visually distracting.

**Comment by calculuschild** [comment]
I think @ericscheid 's color scheme looks really clean :+1: I like it.

@G-Ambatte I agree clicking the same category again should change the sort direction. I think that's pretty standard functionality. Should be easy enough to just add to this PR.

**Comment by Gazook89** [comment]
Okay, I went with @ericscheid's suggestions.  Here is what it looks like:

image

Note, there is a hover state now as well.  Also, I went with the fontawesome 'sort-up' and 'sort-down' icons....they aren't *full-size* carets, but rather a 'top and bottom'.  At first I thought they were too small, but now that clicking on the sort title has the same function as clicking on the caret, I think it doesn't matter.

**Comment by G-Ambatte** [comment]
On an almost completely unrelated note, would a similar rework of the nav bar resolve #2071?

**Comment by Gazook89** [comment]
> On an almost completely unrelated note, would a similar rework of the nav bar resolve #2071?

I have a branch for this as well from a long time ago. I just have to look over it again and see where it is at

**Comment by calculuschild** [comment]
Alright, I have no other comment on this. Looks good!

**Pull request merged**
