### PR TITLE
Prevent loading of undefined renderer or theme theme bundle.

### PR DESCRIPTION
**Pull request by dbolack-ab**
This should solve for #3629 when an invalid path load in turn tries to load "undefined" themes.

### CODE REVIEW

**Comment by G-Ambatte** [comment]
If we instead put a parameter sanity check as a guard clause in the function in `helpers.js`, then we should only have to update a single piece of code in the future, right?

Is there a reason that something like this wouldn't work?

```
const fetchThemeBundle = async (obj, renderer, theme)=>{
	if(!renderer || !theme) return;
	const res = await request
			.get(`/api/theme/${renderer}/${theme}`)
			.catch((err)=>{
				obj.setState({ error: err });
			});
	if(!res) return;
[...]
```

**Comment by dbolack-ab** [comment]
> If we instead put a parameter sanity check as a guard clause in the function in `helpers.js`, then we should only have to update a single piece of code in the future, right?
> 
> Is there a reason that something like this wouldn't work?
> 
> ```
> const fetchThemeBundle = async (obj, renderer, theme)=>{
> 	if(!renderer || !theme) return;
> 	const res = await request
> 			.get(`/api/theme/${renderer}/${theme}`)
> 			.catch((err)=>{
> 				obj.setState({ error: err });
> 			});
> 	if(!res) return;
> [...]
> ```

I can give that a whirl. I tried catching this in a different place at it was uglier. This seems to work better and simpler.

**Comment by calculuschild** [comment]
This doesn't actually address the root issue of #3629. The issue there, is invalid URLs are emitting garbage data. Instead, we unrecognized paths to be rerouted to `/`.

So this PR is probably a good safeguard, but we also need to solve the root issue.

**Comment by calculuschild** [comment]
Seems to work as expected. Thanks!

**Pull request merged**
