### PR TITLE
Update Spell Lists in magic.gen.js for new synta

### PR DESCRIPTION
**Pull request by Gazook89**
Add "1st Level" to levels in spell list.  convert spell list to moustache syntax.

### CODE REVIEW

**Comment by calculuschild** [comment]
What's all this user page 3d stuff? Is that needed for this PR?

**Comment by Gazook89** [comment]
Frack, no. Saved it to wrong branch. If you can remove it, great, or I can when I get back to computer after baby bed time.

**Comment by calculuschild** [comment]
I'll let you handle it. If I modify it myself I would be overwriting your
master branch and I don't want to risk deleting your other work.

**Comment by Gazook89** [comment]
Okay, think it's all set.

**Comment by calculuschild** [comment]
These changes were already included in #1480

**Pull request closed without merging**
